DROP TABLE if exists comments cascade;
DROP TABLE if exists request cascade;
DROP TABLE if exists booking cascade;
DROP TABLE if exists item cascade;
DROP TABLE if exists users cascade;

CREATE TABLE IF NOT EXISTS users (
     user_id bigint generated by default as identity
         constraint user_pk
             primary key,
    name    varchar(50) not null,
    email   varchar(90) not null unique
);

create table if not exists request
(
    request_id   bigint generated by default as identity
        constraint request_pk
            primary key,
    description  varchar(250) not null,
    requestor_id bigint       not null
        constraint request_user_fk
            references users,
    created      timestamp
);

CREATE TABLE IF NOT EXISTS item (
    item_id     bigint generated by default as identity
        constraint item_pk
            primary key,
    name        varchar(50)  not null,
    description varchar(250) not null,
    available   boolean      not null,
    user_id     bigint       not null
        constraint item_user_fk
            references users,
    request_id  bigint
        constraint item_request_fk
            references request
);

create table if not exists booking
(
    booking_id bigint generated by default as identity
        constraint booking_pk
            primary key,
    item_id    bigint  not null
        constraint booking_item_fk
            references item,
    booker_id    bigint  not null
        constraint booking_user_fk
            references users,
    start      timestamp    not null,
    end_rent      timestamp    not null,
    status     varchar
);

create table if not exists comments
(
    comment_id bigint generated by default as identity
        constraint comments_pk
            primary key,
    text       varchar(250) not null,
    item_id    bigint       not null
        constraint comments__fk__item
            references item,
    author_id  bigint       not null
        constraint comments__fk__author
            references users,
    created    timestamp    not null
);